sudo: false

language: python

python:
  - "3.5"

branches:
  only:
    - master

install:
  - pip3 install --upgrade pip
  - pip3 install flake8

script:
  - flake8 --benchmark --statistics
  - python3 setup.py bdist_egg
